# Generated by Django 5.1.4 on 2024-12-09 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название модели"),
                ),
                ("description", models.TextField(verbose_name="Описание модели")),
            ],
            options={
                "verbose_name": "Модель устройства",
                "verbose_name_plural": "Модели устройств",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Введите адрес. Автодополнение с использованием сервиса dadata.ru.",
                        max_length=500,
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название устройства"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(verbose_name="IP-адрес устройства"),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "device_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="device_app.devicemodel",
                        verbose_name="Модель устройства",
                    ),
                ),
            ],
            options={
                "verbose_name": "Устройство",
                "verbose_name_plural": "Устройства",
            },
        ),
    ]
