services:
  main-app:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: main-app
    ports:
      - "8000:8000"
    command: >
      sh -c "python /app/manage.py migrate &&
             python /app/manage.py collectstatic --noinput &&
             python /app/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres
    volumes:
      - ../../:/app
    networks:
      - app_network

  postgres:
    image: postgres:latest
    container_name: netbox_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - app_network

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge